"""
Django settings for router project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1ey380cbsgazbfkyq@(+%q22vu##o!p%-3(^tas*dx*3q^#!9f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cycling.apps.CyclingConfig',
    'OAuth.apps.OauthConfig',
    'user.apps.UserConfig',
    'athlete.apps.AthleteConfig',
    'account.apps.AccountConfig',
    'shared.apps.SharedConfig',
    'location.apps.LocationConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'router.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'router.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

SOCIAL_AUTH_STRAVA_KEY = "c182492544cf54ecb419b3ecc384b197956ca40d" # env('STRAVA_CLIENT_SECRET')
SOCIAL_AUTH_STRAVA_SECRET = "2e4f4988394d4a9623c6a1d371338b57e9b8de02" # env('STRAVA_ACCESS_TOKEN')

STRAVA_API_KEY =   "c182492544cf54ecb419b3ecc384b197956ca40d" # env('STRAVA_CLIENT_SECRET')
GMAPS_API_KEY = "AIzaSyBw9r3MAjAxc3JRmrNljqd_2n4fVobdEzs&=AIzaSyBvxfkviFFrQmLiRuBhg1IXowcksnLF3Ps" # env('GMAPS_API_KEY')
STRAVA_CLIENT_ID = 41327 # os.environ['STRAVA_CLIENT_ID']

STRAVA_AUTH_URL = "https://www.strava.com/oauth/authorize"
STRAVA_ACCESS_TOKEN_URL = "https://www.strava.com/oauth/token"
STRAVA_BASE_URL = "https://www.strava.com"
STRAVA_REFRESH_URL = "https://www.strava.com/oauth/token"
STRAVA_REDIRECT_URL = "http://localhost:8000/oauth/strava_token_exchange"
