# Generated by Django 3.0.6 on 2020-07-09 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0002_auto_20200707_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stravaathlete',
            name='athlete_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='athlete.Athlete'),
        ),
    ]
