# Generated by Django 3.0.6 on 2020-07-09 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0003_auto_20200709_0537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stravaathlete',
            old_name='athlete_id',
            new_name='athlete',
        ),
    ]
