# Generated by Django 3.0 on 2019-12-16 03:52

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[(1, 'ADMIN'), (2, 'USER')], default=user.models.Profile.ProfileTypes['USER'], max_length=100),
        ),
    ]
