# Generated by Django 3.0.6 on 2020-06-06 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200606_0732'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stravaathlete',
            table=None,
        ),
    ]
