# Generated by Django 3.0.6 on 2020-06-30 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycling', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StravaRoute',
        ),
    ]
