# Generated by Django 3.0.6 on 2020-07-04 06:46

import OAuth.OAuthMixin
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athlete', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StravaAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.TextField()),
                ('access_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('token_type', models.TextField()),
                ('auth_url', models.TextField()),
                ('strava_athelete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='athlete.StravaAthlete')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Strava Accounts',
            },
            bases=(models.Model, OAuth.OAuthMixin.OAuthMixin),
        ),
    ]
