# Generated by Django 3.0.6 on 2020-06-06 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200606_0732'),
        ('OAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stravaaccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.StravaAthlete'),
        ),
    ]
