# Generated by Django 3.0.6 on 2020-06-30 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_auto_20200606_0752'),
        ('OAuth', '0002_auto_20200606_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='stravaaccount',
            name='auth_url',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stravaaccount',
            name='strava_athelete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.StravaAthlete'),
        ),
        migrations.AlterField(
            model_name='stravaaccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
