# Generated by Django 3.0 on 2019-12-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OAuth', '0002_oauthtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthtoken',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='oauthtoken',
            name='expires_in',
            field=models.DateTimeField(),
        ),
    ]
