# Generated by Django 3.0 on 2019-12-28 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OAuth', '0003_auto_20191228_0638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauthtoken',
            name='user',
        ),
    ]
