# Generated by Django 3.0.6 on 2020-06-30 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OAuth', '0003_auto_20200630_0203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oauthtoken',
            options={'verbose_name': 'OAuth Tokens'},
        ),
        migrations.AlterModelOptions(
            name='stravaaccount',
            options={'verbose_name': 'Strava Accounts'},
        ),
    ]
