# Generated by Django 3.0.6 on 2020-07-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OAuth', '0004_auto_20200630_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthtoken',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
